Step1
sihwanim/racing-car pull request #1
Opened 2022-03-16 10:47 UTC by sihwa1019

2022-03-16 16:35 UTC, sihwa1019 commented
# [공부한 거 키워드1]

## 배운 것

## 참고 자료

2022-03-16 17:04 UTC, sihwa1019 commented
# [MVC모델]

## 배운 것
1. MVC모델이란?
     - 모델-뷰-컨트롤러(Model-View-Controller)로 이루어진 소프트웨어 디자인패턴
2. 모델(Model)
     - 정보들의 가공을 책임지는 컴포넌트
     - 애플리케이션의 정보, 데이터를 나타내며 모델의 변경사항을 컨트롤러와 뷰에 전달함
     - 규칙
          - 사용자는 편집을 원하는 모든 데이터를 가지고 있어야 함
          - 뷰와 컨트롤러에 대해 어떤 정보도 알고 있으면 안됨
          - 변경이 일어나면, 변경 통지에 대한 처리 방법을 구현해야 함
3. 뷰(View)
      - 사용자에게 보여지는, 유저 인터페이스를 의미함
      - 여러개의 뷰가 존재할 수 있으며 모델에 질의해 데이터를 전달 받음. 이 때, 모델에게 전달받은 데이터를 별도로 저장하면 안됨. 
      - 화면에 표시된 내용을 변경하면 모델에 전달하여 모델을 변경해야 함
      - 규칙
           - 모델의 정보를 따로 저장하면 안됨
           - 모델이나 컨트롤러와 같이 다른 구성요소를 몰라야 함
           - 변경이 일어나면 변경통지에 대한 처리방법을 구현해야 함 
4. 컨트롤러(Controller)
     - 모델과 뷰를 잇는 브릿지 역할
     - 모델과 뷰는 서로의 존재를 모르므로 컨트롤러를 통해 중재한다. 이때 모델과 뷰에 대해 알고 있 
        어야 합니다.
     - 모델이냐 뷰로부터 변경 내용을 통지 받으면 이를 각 구성요소에 통지해야함.
     - 사용자가 어플리케이션을 조작하여 발생하는 변경 이벤트들을 처리함
     - 규칙
          - 모델이나 뷰에 대해 알고 있어야 함
          - 모델이나 뷰의 변경을 모니터링 해야 함
5. MVC 패턴 장점
     - 유지보수가 편리하다.
     - 결합도가 높은 시스템은 유지보수 시 다른 비즈니스 로직에 영향을 미치므로 버그를 유발할 수 
        있다. 
     - 따라서 UI 시스템의 핵심 컴포넌트를 모델, 뷰, 컨트롤러로 나누고 각각의 수행 결과를 다른 컴포 
       넌트에 전달하도록 함.
     - 화면의 변경은 ONLY 뷰, 데이터 혹은 비즈니스 요건 변경은 ONLY 모델, 이에 따른 일부 컨트롤러 
       변경
6. 한계
     - 복잡한 대규모 프로그램의 경우 다수의 뷰와 모델이 컨트롤러로 연결되기 때문에 컨트롤러가 불 
       필요한 경우 발생
## 참고 자료
https://junhyunny.github.io/information/design-pattern/mvc-pattern/

2022-03-19 15:49 UTC, RinSabbit requested changes
시화님 첫 과제 너무 수고하셨어요~~!!~!!
피드백 남겼으니 확인하시고 리팩토링해주세요!!
리팩토링이 끝나면 push 한후 카톡으로 연락 주시면 됩니다ㅎㅎ

2022-03-19 15:49 UTC, bimppap commented on src/main/java/CarRacing/Domain/RacingGameFactory.java
> +import jdk.jshell.EvalException;
쓰이는 곳이 없는 import 네요. 이게 있으면 실행이 안 됐을텐데...? 🤔

2022-03-19 15:49 UTC, bimppap commented on src/main/java/CarRacing/Domain/Cars.java
> +//        }
쓰이지 않는 주석은 지워주세요!

2022-03-19 15:49 UTC, bimppap commented on build.gradle
> +    testImplementation 'org.junit.jupiter:junit-jupiter-params:5.4.2'
중요한건 아니지만 implemetation은 implemetation끼리, runtimeOnly는 runtimeOnly끼리 묶어놓는게 좋아요 :3

2022-03-19 15:49 UTC, bimppap commented on src/main/java/Calculator.java
> +public class Calculator {
전체적으로 코드 포맷팅이 안 된거 같아요!
커밋하기 전에 코드 포맷팅은 꼭 돌려주세요!!
윈도우의 경우 Ctrl + Alt + L 이 자동 정렬 단축키입니다 :3

2022-03-19 15:49 UTC, bimppap commented on src/main/java/App.java
> +        RacingGameController.play();
메인에서 컨트롤러를 쓸 순 없는 걸까요? 컨트롤러를 따로 분리하면 뭐가 좋을지 한번 고민해보는게 좋을 거 같아요.
이 코드가 오답이라는게 아니라 의견을 묻는 거니까 편하게 답해주쉐이 같이 의견 나누면 저도 공부되니까요ㅎㅎ

2022-03-19 15:49 UTC, bimppap commented on src/main/java/CarRacing/Controller/RacingGameController.java
> +    public static void play(){
일반 메소드와 static 메소드의 차이는 뭘까요? static 메소드를 쓰면 관련된 메소드들에게 어떤 영향이 갈까요?

2022-03-19 15:49 UTC, bimppap commented on src/main/java/CarRacing/Domain/Car.java
> +    private Position position = Position.valueOf(0);
final이 안 붙은 이유가 따로 있나요?

2022-03-19 15:49 UTC, bimppap commented on src/main/java/CarRacing/View/RacingGameView.java
> +        final String winnerNames = String.join(LIST_SEPARATOR, winners);
안 쓰이고 있는 변수네요?

2022-03-19 15:49 UTC, bimppap commented on src/main/java/CarRacing/Domain/RacingGameFactory.java
> +import jdk.jshell.EvalException;
커밋을 하기 전에 전체 테스트를 한번씩 돌려보는 습관을 들이면 좋아요!

2022-03-19 15:49 UTC, bimppap commented on src/main/java/CarRacing/Domain/Trial.java
> +                    "숫자는 " + TRIAL_MIN + "이상 " + TRIAL_MAX + "이하여야 합니다.");
String.format을 이용해보는 건 어떨까요? 
단순히 + 하는 것과 format 메소드의 차이를 알아보는 것도 좋을 것 같아요.
찾아보니 [흥미로운 글](https://stackoverflow.com/questions/13815384/string-format-vs-operator)이 있네요 :3

2022-03-19 15:49 UTC, bimppap commented on src/main/java/CarRacing/Domain/Trial.java
> +}
equals 와 hashCode를 쓰는 이유는 무엇일까요? 언제 쓰는 게 좋을까요?

2022-03-19 15:49 UTC, bimppap commented on src/main/java/CarRacing/Utils/RandomUtils.java
> +        return RANDOM.nextInt(10);
하드코딩은 피해주세요!!
참고하시라고 [하드코딩에 관련된 글](https://tecoble.techcourse.co.kr/post/2020-05-07-avoid-hard-coding/)을 두고 갑니다.

2022-03-19 15:49 UTC, bimppap commented on src/main/java/CarRacing/View/RacingGameView.java
> +    private static final Scanner sc = new Scanner(System.in);
static으로 된 맴버는 **모든 객체에서 동시 접근**하게 됩니다.
그렇다면 여러 사람이 동시에 이 게임을 하게 된다면 무슨 일이 벌어질까요?

2022-03-19 15:49 UTC, bimppap commented on src/main/java/CarRacing/Domain/Car.java
> +    private Position position = Position.valueOf(0);
```suggestion
    private static final int MOVABLE_RPM_MIN = 4;

    private final Name name;
    
    private Position position = Position.valueOf(0);
```

다른 키워드끼리 분리하는게 가독성이 좋습니다!

2022-03-19 15:49 UTC, bimppap commented on src/main/java/CarRacing/Domain/Position.java
> +    private static final int Position_min = 0;
static 변수의 경우 대문자를 쓰는 컨벤션이 있습니다 :3
```suggestion
    private static final int POSITION_MIN = 0;
```

2022-03-19 15:49 UTC, bimppap commented on src/main/java/CarRacing/View/RacingGameView.java
> +//        }
주석이 또 👀

2022-03-19 15:49 UTC, bimppap commented on src/main/java/CarRacing/Domain/Cars.java
> +            car.tryToMove(currentRpm);
[전략 패턴](https://victorydntmd.tistory.com/292)에 관해 한번 찾아보면 좋을 것 같아요. 꼭 적용하라는 건 아니지만 참고가 될 수 있을 것 같아요!

2022-03-19 15:49 UTC, bimppap commented on src/main/java/CarRacing/Domain/Cars.java
> +        return new ArrayList<>(cars);
방어적 복사 👍

2022-03-19 15:49 UTC, bimppap commented on src/main/java/CarRacing/Domain/Cars.java
> +        return new ArrayList<>(cars);
unmodifiableList를 쓰는 것도 좋을 것 같아요! 관련 자료를 찾아보고 취향에 맞게 적용해보세요 ><

2022-03-19 15:49 UTC, RinSabbit commented on src/main/java/CarRacing/Domain/RacingGame.java
> +    public List<String> getWinners(){
get을 쓰면 getter처럼 보일 수가 있습니다. 
```suggestion
    public List<String> findWinners(){
```
이게 좀 더 어울리지 않을까요? 추천해봅니다ㅎㅎ
[자바 메소드 명명 규칙](https://ozofweird.tistory.com/entry/Java-%EB%AA%85%EB%AA%85-%EA%B7%9C%EC%B9%99)을 두고 가니 한번 읽어보세요!

2022-03-19 15:49 UTC, RinSabbit commented on src/main/java/CarRacing/Domain/RacingGame.java
> +    public List<String> getWinners(){
get을 쓰면 getter처럼 보일 수가 있습니다. 
```suggestion
    public List<String> findWinners(){
```
이게 좀 더 어울리지 않을까요? 추천해봅니다ㅎㅎ
[자바 메소드 명명 규칙](https://ozofweird.tistory.com/entry/Java-%EB%AA%85%EB%AA%85-%EA%B7%9C%EC%B9%99)을 두고 가니 한번 읽어보세요!

2022-03-19 15:49 UTC, RinSabbit commented on src/main/java/CarRacing/View/RacingGameView.java
> +    private static final String MOVEMENT = "-";
상수화 👍

2022-03-19 15:49 UTC, RinSabbit commented on src/main/java/CarRacing/View/RacingGameView.java
> +    private static final String MOVEMENT = "-";
상수화 👍

2022-03-19 15:49 UTC, RinSabbit commented on src/test/java/RacingGameFactoryTest.java
> +public class RacingGameFactoryTest {
이 테스트에서 Name, Cars, Trial 클래스들의 검증이 모두 이뤄지고 있네요.
개인적으로 이 경우 각각의 테스트들은 NameTest, CarsTest, TrialTest를 만들어서 각 테스트에서 확인하는게 맞다고 봅니다.
이러면 요구사항이 추가될때 해당 테스트의 규모가 과도하게 커질 수 있을 것 같아서요.

개인 의견이니 참고만 해주세요!

2022-03-19 15:49 UTC, RinSabbit commented on src/test/java/RacingGameFactoryTest.java
> +public class RacingGameFactoryTest {
이 테스트에서 Name, Cars, Trial 클래스들의 검증이 모두 이뤄지고 있네요.
개인적으로 이 경우 각각의 테스트들은 NameTest, CarsTest, TrialTest를 만들어서 각 테스트에서 확인하는게 맞다고 봅니다.
이러면 요구사항이 추가될때 해당 테스트의 규모가 과도하게 커질 수 있을 것 같아서요.

개인 의견이니 참고만 해주세요!

2022-03-19 15:49 UTC, RinSabbit commented on src/test/java/RacingGameTest.java
> +                    Arrays.asList("루트", "소롱", "포비"))
익숙한 이름들이 보이네요ㅋㅋㅋ

2022-03-19 15:49 UTC, RinSabbit commented on src/test/java/RacingGameTest.java
> +                    Arrays.asList("루트", "소롱", "포비"))
익숙한 이름들이 보이네요ㅋㅋㅋ

2022-03-19 15:49 UTC, RinSabbit commented on src/main/java/CarRacing/Controller/RacingGameController.java
> +    public static void play(){
> G18: 부적절한 static 함수
모든 정보를 인수에서 가져온다면 static으로 선언한다. 하지만 함수를 재정의할 가능성이 존재한다면 인스턴스 메서드로 선언해라. 조금 의심스럽다면 인스턴스 함수로 정의해라. 그래도 static으로 하고 싶으면 제정의할 가능성이 없는지 꼼곰히 따져봐라.

출처 : [Clean Code 17. Code smell & heuristic](https://devstarsj.github.io/study/2018/12/15/study.cleanCode.17/) or 클린코드 p. 381

2022-03-19 15:49 UTC, RinSabbit commented on src/main/java/CarRacing/Controller/RacingGameController.java
> +    public static void play(){
깜짝 과제(^^)를 드려볼게요. 컨트롤러에서 static 메소드들을 전부 없애봅시다!

2022-03-19 15:49 UTC, RinSabbit commented on src/test/java/RacingGameTest.java
> +    }
이렇게 테스트를 하는 방법도 있군요 👀

2022-03-19 15:49 UTC, RinSabbit commented on src/test/java/RacingGameTest.java
> +    }
이렇게 테스트를 하는 방법도 있군요 👀

2022-03-19 15:49 UTC, RinSabbit commented on src/main/java/CarRacing/Domain/Cars.java
> +public class Cars {
일급컬렉션 👍

2022-03-19 15:49 UTC, RinSabbit commented on src/main/java/CarRacing/Domain/Cars.java
> +public class Cars {
일급컬렉션 👍

2022-03-19 15:49 UTC, RinSabbit commented on src/main/java/CarRacing/View/RacingGameView.java
> +        return result;
```suggestion
        return sc.nextLine();
```
가독성에 문제가 없다면 바로 리턴을 하는 것도 좋습니다 :)

2022-03-19 15:49 UTC, RinSabbit commented on src/main/java/CarRacing/View/RacingGameView.java
> +        return result;
```suggestion
        return sc.nextLine();
```
가독성에 문제가 없다면 바로 리턴을 하는 것도 좋습니다 :)

2022-03-19 15:49 UTC, RinSabbit commented on src/main/java/CarRacing/Domain/Cars.java
> +        return cars.stream()
스트림 👍 람다도 잘 적용해주셨네요!

2022-03-19 15:49 UTC, RinSabbit commented on src/main/java/CarRacing/Domain/Cars.java
> +        return cars.stream()
스트림 👍 람다도 잘 적용해주셨네요!

2022-03-19 15:49 UTC, RinSabbit commented on src/main/java/CarRacing/Domain/Cars.java
> +    private static void validateNumberOfCars(final List<Car> cars) {
static 인 이유가 있나요?

2022-03-19 15:49 UTC, RinSabbit commented on src/main/java/CarRacing/Domain/Cars.java
> +    private static void validateNumberOfCars(final List<Car> cars) {
static 인 이유가 있나요?

2022-03-19 15:49 UTC, RinSabbit commented on src/main/java/CarRacing/Domain/Cars.java
> +    private static void validateNumberOfCars(final List<Car> cars) {
클래스 내 메소드 배치 순서를 아래 같이 하면 가독성이 더 좋아져요.
```
class A {
    상수(static final) 또는 클래스 변수
    인스턴스 변수
    생성자
    팩토리 메소드
    메소드
    기본 메소드 (equals, hashCode, toString)
}
```

2022-03-19 15:49 UTC, RinSabbit commented on src/main/java/CarRacing/Domain/Cars.java
> +            car.tryToMove(currentRpm);
해당 메소드를 테스트하려면 어떻게 해야 할까요?

2022-03-19 15:49 UTC, RinSabbit commented on src/main/java/CarRacing/Domain/Cars.java
> +            car.tryToMove(currentRpm);
Car가 움직일 수 있는지 정해주는 currentRpm을 외부에서 주입해주고 있네요.

상황을 가정해봅시다.

1) 자동차에게 숫자를 보여주고 움직일 수 있으면 움직이고, 움직일 수 없으면 움직이지 말라고 한다.
2) 자동차에게 움직일 수 있으면 움직이라고 하자, 본인의 조건에 맞춰 알아서 움직이든가 말든가 한다.
어느 쪽이 정답이라곤 할 순 없습니다. 상황에 따라 요구사항은 달라지니까요!
하지만 이 경우 랜덤이 아닌 고정된 값을 입력받는 자동차도 추가해달라고 하면 어떻게 수정해야 할까요?

어떻게 코드를 짜면 요구사항이 추가되거나 변경됐을때 코드를 최소한으로만 변경할 수 있을지 고민해봅시다.

2022-03-19 15:49 UTC, RinSabbit commented on src/main/java/CarRacing/View/RacingGameView.java
> +public class RacingGameView {
현재 RacingGameView에서 입출력을 모두 담당하고 있네요.
입력과 출력은 엄연히 다른 역할을 가지고 있어요.
아래 구조처럼 입력View와 출력View를 분리해보는 건 어떨까요?

![image](https://user-images.githubusercontent.com/48675973/159127786-529f73be-3087-40ca-8195-1a78db32c19e.png)

2022-03-19 15:49 UTC, RinSabbit commented on src/main/java/CarRacing/View/RacingGameView.java
> +public class RacingGameView {
현재 RacingGameView에서 입출력을 모두 담당하고 있네요.
입력과 출력은 엄연히 다른 역할을 가지고 있어요.
아래 구조처럼 입력View와 출력View를 분리해보는 건 어떨까요?

![image](https://user-images.githubusercontent.com/48675973/159127786-529f73be-3087-40ca-8195-1a78db32c19e.png)

2022-03-19 15:49 UTC, RinSabbit commented on src/main/java/CarRacing/Domain/Position.java
> +public class Position {
Position을 추상화했네요! 👍 
다만 이런 VO(Value Object)는 항상 eqauls & hashcode 구현을 동반해야 해요.
왜 그럴까요? :)

2022-03-19 15:49 UTC, RinSabbit commented on src/main/java/CarRacing/Domain/Position.java
> +public class Position {
Position을 추상화했네요! 👍 
다만 이런 VO(Value Object)는 항상 eqauls & hashcode 구현을 동반해야 해요.
왜 그럴까요? :)

2022-03-19 15:49 UTC, RinSabbit commented on src/main/java/CarRacing/Domain/Name.java
> +        if(name.length()>NAME_LENGTH_MAX || name.length() < NAME_LENGTH_MIN){
if 내 조건문이 길어지면 메소드로 빼는 것도 좋습니다 :)

2022-03-19 15:49 UTC, RinSabbit commented on src/main/java/CarRacing/Domain/Name.java
> +        if(name.length()>NAME_LENGTH_MAX || name.length() < NAME_LENGTH_MIN){
if 내 조건문이 길어지면 메소드로 빼는 것도 좋습니다 :)

2022-03-27 15:34 UTC, sihwa1019 commented on src/main/java/CarRacing/View/RacingGameView.java
> +        return result;
앗 이해했습니다! 하지만 저는 result로 깔끔하게 하는게 더 취향인것 같아서 유지해도 괜찮을까요?

2022-03-27 15:49 UTC, sihwa1019 commented on src/main/java/CarRacing/View/RacingGameView.java
> +    private static final Scanner sc = new Scanner(System.in);
static을 사용하면 메모리에 값이 할당되어 프로그램 종료시에 해제됩니다.
이때 static 필드를 공유하게 됩니다.
따라서, 모든 객체에서 동시 접근하게 되면 한 스레드에서 값을 변경할 때 다른 모든 스레드에 영향을 받아 에러가 나지 않을까요!

2022-03-28 00:36 UTC, RinSabbit commented on src/main/java/CarRacing/View/RacingGameView.java
> +        return result;
당연하죠S2

2022-03-29 12:07 UTC, sihwa1019 commented on src/main/java/CarRacing/Controller/RacingGameController.java
> +    public static void play(){
변경했습니다. controller에서 static을 제외하고 app에서 에러가 생겼습니다. main함수를 static으로 변경해서 해결했습니다! 정상작동!

2022-03-29 12:15 UTC, sihwa1019 commented on src/main/java/CarRacing/Utils/RandomUtils.java
> +        return RANDOM.nextInt(10);
오 하드코딩이 이런거였군요! 확실히 변수를 따로 빼면 나중에 수정하기가 좋다는 느낌이 듭니다!

2022-03-29 12:20 UTC, sihwa1019 commented on src/main/java/CarRacing/Domain/Cars.java
> +        return new ArrayList<>(cars);
이 링크를 [참고](https://velog.io/@miot2j/%EC%96%95%EC%9D%80%EB%B3%B5%EC%82%AC-%EA%B9%8A%EC%9D%80%EB%B3%B5%EC%82%AC-%EB%B0%A9%EC%96%B4%EC%A0%81-%EB%B3%B5%EC%82%AC%EB%9E%80)해서 공부합니다!

2022-03-29 12:27 UTC, sihwa1019 commented on src/main/java/CarRacing/Domain/Cars.java
> +    private static void validateNumberOfCars(final List<Car> cars) {
static을 빼도 문제가 없네용!

2022-03-29 12:37 UTC, sihwa1019 commented on src/main/java/CarRacing/View/RacingGameView.java
> +public class RacingGameView {
오...RacingInputView랑 RacingOutputView로 분리했어요~!

2022-04-16 07:45 UTC, merged