Step1 완료!
sihwanim/racing-car pull request #2
Opened 2022-03-28 02:39 UTC by amane-IT

2022-03-31 06:16 UTC, RinSabbit requested changes
아마네님 넘 수고하셨어요!! 피드백 남겼으니까 다 고치고 push 한 이후에 카톡으로 말해주세요!!
혹시 모르거나 헷갈리는 부분 있으면 역시 카톡으로 편하게 물어봐주세요!!

2022-03-31 06:16 UTC, bimppap commented on src/main/java/Application.java
> +public class Application {
전체적으로 코드 포맷팅이 덜 된 것 같아요.
[이 링크](https://velog.io/@injoon2019/IntelliJ%EC%97%90-Google-Java-Style-Guide-%EC%A0%81%EC%9A%A9%ED%95%98%EA%B8%B0)를 참고하고 전체적으로 코드 포맷팅을 해봅쉬다 :3

2022-03-31 06:16 UTC, bimppap commented on src/main/java/Calculator.java
> +			throw new ArithmeticException("0으로 나눌 수 없습니다.");
ArithemticException으로 한 이유가 있을까요?

2022-03-31 06:16 UTC, bimppap commented on src/main/java/Calculator.java
> +			throw new ArithmeticException("0으로 나눌 수 없습니다.");
[표준 예외 vs 커스텀 예외](https://tecoble.techcourse.co.kr/post/2020-08-17-custom-exception/) 에 대해 읽어보고 어느 쪽이 본인에게 맞을지 한번 고민해보면 좋을 것 같습니다!

2022-03-31 06:16 UTC, bimppap commented on src/main/java/controller/Controller.java
> +	private List<Car> getCars(){
getter/setter에는 로직이 들어가면 안됩니다!
이건 getter/setter 보다는 특정 기능을 하는 메소드니 `getCars`보다는 `inputCars같은 이름으로 바꿔주는 게 좋을 것 같아용

2022-03-31 06:16 UTC, bimppap commented on src/main/java/controller/Controller.java
> +		} catch (IllegalArgumentException e){
지금은 프로젝트 사이즈가 작지만 프로젝트가 커지면 에러가 발생했을때 발생 구간을 찾기 어려울 수도 있을 것 같아요.
간단하게라도 출력이 되게끔 해봅시다!

2022-03-31 06:16 UTC, bimppap commented on src/main/java/model/Car.java
> +	private int position;
```suggestion
	private final String name;
	
	private int position;
```

키워드 종류가 달라지면 띄워쓰기로 분류해놓는게 좋아용

2022-03-31 06:16 UTC, bimppap commented on src/main/java/model/Car.java
> +public class Car {
클래스 내 배치 순서는 아래처럼 하는 게 보기 좋습니다!!

```
class A {
    상수(static final) 또는 클래스 변수
    인스턴스 변수
    생성자
    팩토리 메소드
    메소드
    기본 메소드 (equals, hashCode, toString)
}
```

2022-03-31 06:16 UTC, bimppap commented on src/main/java/model/Cars.java
> +public class Cars {
일급컬렉션 👍

2022-03-31 06:16 UTC, bimppap commented on src/main/java/model/Cars.java
> +	 	for(Car c : cars){
자바8부터 [스트림](https://velog.io/@gmtmoney2357/%EC%9E%90%EB%B0%94-%EC%8A%A4%ED%8A%B8%EB%A6%BCStream)을 사용할 수 있게 되었는데, 스트림을 쓸 때도 있고 for문, for-each문을 쓸 때도 있네요. 기준이 따로 있을까요? 👀

2022-03-31 06:16 UTC, bimppap commented on src/main/java/model/Cars.java
> +			.orElse(-1);
-1을 받게 되면 무슨 일이 일어나나요?

2022-03-31 06:16 UTC, bimppap commented on src/main/java/model/Cars.java
> +			.orElse(-1);
```suggestion
	public int getFartherestPosition(){
	 	return cars.stream()
			.map(Car::getPosition)
			.max(Integer::compare)
			.orElseThrow(IllegalArgumentException::new);
```
요런 방법도 있답니다 :3

2022-03-31 06:16 UTC, bimppap commented on src/main/java/model/Cars.java
> +			.orElse(-1);
getter/setter가 아니면 웬만하면 get/set으로 시작하는 메소드명을 만들지 마세요. 
[메소드 명명 규칙](https://ozofweird.tistory.com/entry/Java-%EB%AA%85%EB%AA%85-%EA%B7%9C%EC%B9%99)을 읽어보면 좋을 것 같아요!

2022-03-31 06:16 UTC, bimppap commented on src/main/java/util/generator/NameGenerator.java
> +	public static final String DELIMITER = ",";
상수화 👍

2022-03-31 06:16 UTC, bimppap commented on src/main/java/util/validator/Validator.java
> +		if(input.equals(null)){
```suggestion
		if(input == null){
```
equals와 ==의 차이에 대해 알아두면 좋을 것 같아요 :3

2022-03-31 06:16 UTC, bimppap commented on src/main/java/util/validator/RandomGoForward.java
> +public class RandomGoForward {
이 클래스가 validator에 해당하나요?

2022-03-31 06:16 UTC, bimppap commented on src/main/java/model/Car.java
> +package model;
MVC 모델을 썼군요!! 👍  이 경우 패키지명은 `domain`이라 하는게 주류입니다!

2022-03-31 06:16 UTC, bimppap commented on src/main/java/util/validator/TrailNumberValidator.java
> +	}
`is~` 식의 메소드명은 리턴값이 boolean일때 주로 사용해요! 적절한 메소드명에 대해 한번 고민해봅시다.

2022-03-31 06:16 UTC, bimppap commented on src/main/java/util/validator/Validator.java
> +public class Validator {
Validator을 사용할 때 상속을 사용했군요!! 👍

2022-03-31 06:16 UTC, bimppap commented on src/test/java/racingCar/model/CarsTest.java
> +	Cars cars;
private 같은 접근제한자를 붙여야 하지 않을까요? 접근제한자가 없으면 무슨 일이 일어날까요?

2022-03-31 06:16 UTC, bimppap commented on src/test/java/CalculatorTest.java
> +	}
사용하지 않는 주석은 삭제합시다! 요런 필기 매우 good good 이지만 PR이후 코멘트로 남기거나 블로그 같은 데 정리하는 게 좋을 거 같아요!! (요즘은 개발 블로그 보는 경우도 많아서...-,.-

2022-03-31 06:16 UTC, bimppap commented on src/main/java/util/validator/NameValidator.java
> +	}
이건 Name보다는 Cars를 검증하는 로직같네요 👀

2022-03-31 06:16 UTC, bimppap commented on src/main/java/util/validator/RandomGoForward.java
> +	}
랜덤값이 나오는 이 로직을 테스트하려면 어떻게 해야 할까요?

힌트
- 테스트하기 힘든 부분과 쉬운 부분을 분리해보자
- 테스트하기 힘든 부분은 외부에서 주입하도록 하자
- (옵션) 인터페이스를 활용해보자 <- 전략패턴을 검색해보면 느낌이 올 지도 모르겠네오

2022-03-31 06:16 UTC, bimppap commented on src/main/java/util/validator/RandomGoForward.java
> +	}
```suggestion
	public static boolean goFoward(){
		return random.nextInt(RANGE_NUMBER) >= 4;
	}
```

2022-03-31 06:16 UTC, bimppap commented on src/main/java/util/validator/RandomGoForward.java
> +	}
4같은 상수는 하드코딩입니다! 상수화해주세요!

2022-03-31 06:16 UTC, bimppap commented on src/main/java/model/Cars.java
> +	 	int fartherest = getFartherestPosition();
```suggestion
	 	int farthest = getFarthestPosition();
```

2022-03-31 06:16 UTC, bimppap commented on src/main/java/model/Cars.java
> +			.max(Integer::compare)
람다식 👍

2022-03-31 06:16 UTC, bimppap commented on src/main/java/model/Car.java
> +	private int position;
Car의 경우 필드 변수로 name을 가지고 있네요. name의 검증은 **어디서** 이루어져야 할까? 에 대해 고민해봅시다.
현재 Cars에서도 validateNames로 이름들을 검증하고 있고, Car에서는 validateName을 통해 이름을 검증하고 있습니다.

이를 개선시킬 방법이 있을까요?

힌트로 아래 글을 공유해봅니다!!
[객체지향 생활체조 제 3 원칙: 모든 원시값과 문자열을 포장하라](https://tecoble.techcourse.co.kr/post/2020-05-29-wrap-primitive-type/)

2022-03-31 06:16 UTC, bimppap commented on src/main/java/model/Car.java
> +	private int position;
_객체지향적인 코드란 무엇인가?_ 에 대해 감이 안 잡힐 수도 있어요. 저 같은 경우엔 이런 식의 사고가 좀 더 방향을 잡아줬습니다.

> 이름이 검증되야 한다는 걸 Car가 알아야 할까?
> Car에게 달리라는 메세지를 보낼 때, 외부에서 인수로 canGo를 주입하는 게 맞는가? 알아서 달릴 필요는 없는가?

좀 더 전문적으로 표현을 해보자면 이렇게 말할 수도 있겠네요.

> 자율적인 객체란 스스로의 의지와 판단에 따라 각자 맡은 책임을 수행하는 객체를 의미한다. 이런 자율적인 객체는 객체지향 공동체를 구성하는 기본 단위이다. 객체지향 설계에서 적절한 책임을 적절한 객체에게 할당해야 한다. 적절한 책임이 자율적인 객체를 낳고, 자율적인 객체들이 모여 유연하고 단순한 협력을 낳는다. 따라서 객체의 자율성이 전체 애플리케이션의 품질을 결정한다. - _객체지향의 사실과 오해, 5장. 책임과 메세지_

2022-03-31 06:16 UTC, bimppap commented on src/main/java/view/OutputView.java
> +			System.out.print("-");
요구사항이 차의 distance를 `-`가 아닌 `&`로 변경하라고 하면 찾기가 어려울 수도 있겠네요. 이런 경우도 상수화해주는 게 좋습니다!

2022-03-31 06:16 UTC, bimppap commented on src/main/java/view/OutputView.java
> +	}
```suggestion
        // (1) Stream 활용
	public static void printWinner(List<String> winners){
	String allWinners = winners.stream()
            .collect(Collectors.joining(", "));
        System.out.println(allWinners + WINNER_MESSAGE);
        
        // (2) 자바11부터 사용가능한 String.join 메서드
        String allWinners = String.join(", ", winners);
        System.out.println(allWinners + WINNER_MESSAGE);
        
	}
```

2022-03-31 06:16 UTC, RinSabbit commented on src/main/java/controller/Controller.java
> +	}
```suggestion
	private int getTrialNumber() throw IllegalArgumentExcetion {
		String input = InputView.getTrialNumber();
			return TrialNumberGenerator.generateTrialNumber(input);
	}
```

이렇게 바꾸고 최상단에서 try-catch로 전부 잡아내는 방법도 있어요.
이걸 checked exception, unchecked exception으로 분리해서 나눠 볼 수 있는데,
자세한 이야기는 [예외 처리 전략](https://www.nextree.co.kr/p3239/)에 대해 찾아보면 좋을 것 같네요.
정답은 없으니 본인 취향에 맞게 고쳐보면 좋을 것 같습니다.

2022-03-31 06:16 UTC, RinSabbit commented on src/test/java/racingCar/model/CarTest.java
> +public class CarTest {
테스트 꼼꼼하게 짰네용 👍

2022-03-31 06:16 UTC, RinSabbit commented on src/main/java/view/InputView.java
> +	private static final Scanner sc;
scanner가 static으로 만들어지면 여러 명이 동시에 자동차 이름을 입력하려고 할 때 무슨 일이 벌어질까요?

2022-03-31 06:16 UTC, RinSabbit commented on src/main/java/view/InputView.java
> +	public static String getCarNames(){
```suggestion
	public static String inputCarNames(){
```

get~ 은 지양해주세요!

2022-04-17 10:50 UTC, amane-IT commented on src/main/java/Calculator.java
> +			throw new ArithmeticException("0으로 나눌 수 없습니다.");
> ArithemticException으로 한 이유가 있을까요?

A) ArithmeticException을 사용하면 숫자를 0으로 나누는 경우를 잡아낼 수 있기 때문입니다.
DivideByZeroException을 사용하면 정수 나누기에서 0이 사용된 경우만 잡아내기 때문에 더 넓은 범위인 ArithmeticException을 사용하였습니다. :)

2023-08-06 05:37 UTC, closed without merging