Step01
sihwanim/racing-car pull request #3
Opened 2023-08-06 05:36 UTC by amane-IT

stream이.. 정상작동하지 않아요..

2023-08-13 09:15 UTC, bimppap requested changes
전체적으로 깔끔하게 짰네요 👍 
피드백 남겼으니 리팩토링 후에 재요청 주세요

2023-08-13 09:15 UTC, bimppap commented on src/main/java/controller/Controller.java
> +		// 1. 초기화
복잡한 로직으로 주석 아니면 이해가 어려운 수준이 아니면 주석은 제거해도 됩니다

2023-08-13 09:15 UTC, bimppap commented on src/main/java/domain/Car.java
> +	private static final int INIT_POSITION = 0;
name이랑 position은 final 안 붙인 이유가 있을까요?

2023-08-13 09:15 UTC, bimppap commented on src/main/java/domain/Cars.java
> +	public static List<Car> splitNames(String carNames) {
static 붙은 메서드들은 static이 필수인지 한번 체크 부탁드립니다

2023-08-13 09:15 UTC, bimppap commented on src/main/java/domain/Name.java
> +	public static void validator(String name) {
메서드는 동사를 쓰는게 일반적인 컨벤션인데 validator로 사용한 이유가 있을까요?

2023-08-13 09:15 UTC, bimppap commented on src/main/java/util/RandomUtil.java
> +		int randomNumber = random.nextInt(MAX_RANGE - MIN_RANGE) + MIN_RANGE;
MIN_RANGE 는 0이라서 더하지 않아도 결과값은 같을 것 같습니다

2023-08-13 09:15 UTC, bimppap commented on src/test/java/CarTest.java
> +public class CarTest {
테스트 굿굿 👍

2023-08-13 09:15 UTC, bimppap commented on src/test/java/CarTest.java
> +public class CarTest {
전반적으로 네가티브 테스트(예외상황을 발생시키는 테스트)도 추가하면 좋을 것 같습니다

2023-08-13 09:15 UTC, bimppap commented on src/test/java/CarsTest.java
> +	}
자동차 이름이 각각 a,b,c인 것도 증명하면 더 좋은 테스트가 될 것 같아요

2023-08-13 09:15 UTC, bimppap commented on src/main/java/domain/Cars.java
> +import java.util.ArrayList;
사용하지 않는 import는 제거해주세요

2023-08-13 09:15 UTC, bimppap commented on src/main/java/domain/Cars.java
> +	private List<Car> cars;
전반적으로 final 붙일 수 있는 변수들을 체크해보면 좋을 것 같습니다

2023-08-13 09:15 UTC, bimppap commented on src/main/java/domain/TrialNumber.java
> +public class TrialNumber {
래퍼 클래스 👍

2023-08-13 09:15 UTC, bimppap commented on src/test/java/PositionTest.java
> +	}
~이상, ~이하가 붙은 테스트는 반드시 car.goForward(4) 처럼 경계점으로 테스트를 해봐야 합니다.

2023-08-13 09:15 UTC, bimppap commented on src/test/java/PositionTest.java
> +		Assertions.assertEquals(originPosition, car.getPosition());
@ ParemeterizedTest를 사용하면 2개의 테스트를 하나로 줄일 수 있을 것 같습니다

2023-08-13 09:15 UTC, bimppap commented on src/main/java/domain/Car.java
> +	}
Car입장에선 받는 숫자가 랜덤인지 아닌지 알 필요가 없을 것 같네요

2023-08-13 09:15 UTC, bimppap commented on src/test/java/NameTest.java
> +	}
실패하는 테스트입니다

2023-08-13 09:15 UTC, bimppap commented on src/test/java/CarTest.java
> +public class CarTest {
test 파일에서 마우스 우측 버튼을 누르면 아래처럼 테스트 커버리지를 포함한 전체 테스트 돌리기를 할 수 있습니다.

<img width="807" alt="image" src="https://github.com/sihwanim/racing-car/assets/48675973/3f7bc1e8-7698-4762-a77f-59f0314e4222">

각 객체의 테스트 퍼센티지와 테스트 되지 않은 메서드(라인별 녹색, 붉은색 표시)도 확인할 수 있습니다.
<img width="1002" alt="image" src="https://github.com/sihwanim/racing-car/assets/48675973/8865e9c0-d830-4ad0-9bcf-cf7ccc13e58b">

도메인은 게터, 세터를 제외하곤 웬만하면 전부 테스트하는 게 좋습니다.

2023-08-13 09:15 UTC, bimppap commented on src/main/java/domain/Position.java
> +		}
저는 이 조건은 Position보단 Car이 갖고 있는게 맞다고 생각하는데 의견이 궁금합니다!

2023-08-20 05:15 UTC, amane-IT commented on src/main/java/controller/Controller.java
> +		// 1. 초기화
로직 순서 적어뒀던 것을 지우는 걸 까먹었습니다. 해당 주석들은 제거하도록 하겠습니다.

2023-08-26 14:45 UTC, amane-IT commented on src/main/java/domain/Position.java
> +		}
해당 조건이 Position과 관련된 조건이라 Car보다는 Position에서 관리하는 게 맞다고 생각되어 넣었습니다!

2023-08-26 15:20 UTC, amane-IT commented on src/main/java/util/RandomUtil.java
> +		int randomNumber = random.nextInt(MAX_RANGE - MIN_RANGE) + MIN_RANGE;
나중에 이동가능 범위 변경 등 확장성을 위해 넣은 부분이었습니다!

2023-08-27 08:37 UTC, bimppap approved these changes
굿굿! 수고했습니다!!

2023-08-27 08:37 UTC, bimppap commented on src/main/java/domain/Name.java
>  			throw new IllegalArgumentException(name + LENGTH_ERROR_MESSAGE);
private으로 바꿔도 될 것 같습니다.
static도 빼도 될듯..?

2023-08-27 08:53 UTC, merged