랑 1주차
sihwanim/racing-car pull request #4
Opened 2023-08-06 05:37 UTC by DyeonKim

## 해야할 일
- 임의로 처리한 예외사항들을 에러메시지 출력 후 다시시도하게 변경
- GameController의 역할에 맞지 않는 메소드들이 포함되어 있음. 이를 분리

<br /><br />

commit이 너무 많아져서 수정사항 말해주시면 수정본은 새로운 PR을 생성해서 올리겠습니다.

2023-08-13 09:45 UTC, bimppap requested changes
예외 처리도 해주면 로직 상 문제될 부분은 없어질 것 같습니다!
리팩토링 후 재요청 주세요 👍

2023-08-13 09:45 UTC, bimppap commented on src/main/java/racing_car/controller/GameController.java
> +        for (int t = 1; t <= tryCount; t++) {
```suggestion
        for (int i = 0; i < tryCount; i++) {
```

for문 조건식에 들어가는 변수는 i,j,k를 쓰는게 일반적입니다.
특수한 케이스가 아니면 초기값은 0, 조건문은 < 을 사용합니다.

2023-08-13 09:45 UTC, bimppap commented on src/main/java/racing_car/domain/car/Car.java
> +    }
테스트에서만 쓰이는 메서드는 웬만하면 없애주세요

2023-08-13 09:45 UTC, bimppap commented on src/main/java/racing_car/domain/car/Cars.java
> +        car.go(car.isGo(num));
변수에서 줄임말은 가독성을 떨어트릴 수 있기 때문에 지양해주세요

2023-08-13 09:45 UTC, bimppap commented on src/main/java/racing_car/utils/StringUtil.java
> +        return s.length() <= limitLen ? s : s.substring(0, limitLen);
가독성을 위해 삼항연산자는 지양해주세요

2023-08-13 09:45 UTC, bimppap commented on src/main/java/racing_car/view/OutputView.java
> +            String distance = MOVE_DISTANCE_UNIT.repeat(car.getPosition());
repeat 👍

2023-08-13 09:45 UTC, bimppap commented on src/main/java/racing_car/domain/car/Car.java
> +    private int position;
name, position도 래퍼 클래스로 만드는 건 어떨까요?

2023-08-13 09:45 UTC, bimppap commented on src/main/java/racing_car/domain/car/Car.java
> +    private int position;
eq, hc 도 추가하면 좋을 것 같습니다

2023-08-13 09:45 UTC, bimppap commented on src/main/java/racing_car/domain/car/Car.java
> +    private int position;
클래스 내 배치 순서는 아래와 같이 맞춰주면 가독성이 더 좋을 것 같습니다 :)
```java
class A {
    상수(static final) 또는 클래스 변수
    인스턴스 변수
    생성자
    팩토리 메소드
    메소드
    기본 메소드 (equals, hashCode, toString)
}
```
다른 클래스들도 순서를 맞춰주면 좋을 것 같아요.

2023-08-13 09:45 UTC, bimppap commented on src/test/java/racing_car/domain/car/CarsTest.java
> +        });
이건 CarsTest보단 NumberUtilTest에 가깝지 않을까요?

2023-08-13 09:45 UTC, bimppap commented on src/main/java/racing_car/domain/car/Cars.java
> +    }
랜덤이라는 특성상 테스트하기가 어려울 거 같은데, [전략 패턴]([url](https://victorydntmd.tistory.com/292))을 사용해 해결할 수도 있을 것 같네요.

```java
public interface MovableStrategy {
    boolean isMove();
}

```

2023-08-13 09:45 UTC, bimppap commented on src/main/java/racing_car/domain/car/Cars.java
> +    private final int RANDOM_UNDER = 10;
이건 Cars가 알 필요가 없을 것 같습니다. NumberUtil로 옮겨도 되지 않을까요?

2023-08-13 09:45 UTC, bimppap commented on src/test/java/racing_car/domain/car/CarsTest.java
> +
@ ParemterizedTest를 사용하면 하나의 테스트로 합칠 수 있을 것 같습니다

2023-08-13 09:45 UTC, bimppap commented on src/test/java/racing_car/domain/car/CarsTest.java
> +
조건이 4 이상이면 4라는 경계값도 반드시 테스트해봐야 합니다

2023-08-13 09:45 UTC, bimppap commented on src/main/java/racing_car/view/InputView.java
> +public class InputView {
InputView, OutputView는 정적이기 때문에 static하게 가도 됩니다.

2023-08-13 09:57 UTC, bimppap commented on README.md
> +## 기능목록
👍 👍 👍

2023-08-13 10:27 UTC, amane-IT commented on src/main/java/racing_car/Application.java
> +        GameController gameController = new GameController(scanner);
Scanner객체가 다른 곳에서 쓰이는 게 아니라면 new GameController(new Scanner(System.in))로 처리해도 괜찮지 않을까요?

2023-08-27 01:17 UTC, DyeonKim commented on src/main/java/racing_car/Application.java
> +        GameController gameController = new GameController(scanner);
> Scanner객체가 다른 곳에서도 쓰이는 게 아니라면 new GameController(new Scanner(System.in))로 처리해도 괜찮지 않을까요?

아 이거 Scanner close가 자동으로 되긴해도 명시해주는 게 좋다고 하길래 적었습니다.

2023-08-27 01:18 UTC, DyeonKim commented on src/main/java/racing_car/domain/car/Cars.java
> +    }
> 랜덤이라는 특성상 테스트하기가 어려울 거 같은데, 전략 패턴을 사용해 해결할 수도 있을 것 같네요.
> 
> ```java
> public interface MovableStrategy {
>     boolean isMove();
> }
> ```

전략 패턴이 뭔지 읽어봐도 코드에 적용하려니 어렵네요...ㅠ

2023-08-27 08:53 UTC, bimppap approved these changes
에러랑 처리 방면에서 신경 많이 쓴 게 느껴지네요!
코멘트 간단하게 남기긴 했는데 반드시 반영할 필욘 없는 거라 머지하도로 하겠습니다.
넘넘 수고하셨습니다! 👍 👍 👍

2023-08-27 08:53 UTC, bimppap commented on src/main/java/racing_car/domain/Cars.java
> +
goCar는 goCars에서 car에 메세지를 보내는 방식으로 변경하면 좋을 것 같습니다

2023-08-27 08:53 UTC, bimppap commented on src/main/java/racing_car/domain/car/Name.java
> +public class Name {
name 래퍼 클래스 👍

2023-08-27 08:53 UTC, merged