시화 - 자동차경주 구현
sihwanim/racing-car pull request #8
Opened 2023-08-25 16:27 UTC by SoyoungLee0918

2023-08-25 16:45 UTC, bimppap requested changes
수고하셨습니다. 피드백 남겼으니 확인하고 리팩토링 후 재요청 주세요.
코드를 추가로 더 구현하셔도 됩니다.

2023-08-25 16:45 UTC, bimppap commented on src/main/java/CarRacing/Controller/RacingGameController.java
> +    }
이건 없어도 되지 않나요?

2023-08-25 16:45 UTC, bimppap commented on src/main/java/CarRacing/Controller/RacingGameController.java
> +            System.out.println();
이런 개행은 outputview에서 처리해도 될 것 같아요!

2023-08-25 16:45 UTC, bimppap commented on src/main/java/CarRacing/Controller/RacingGameController.java
> +        String inputName = RacingGameInputView.MessageName();
메서드명은 동사형으로 쓰는 컨벤션이 있습니다. 이건 명사형 같아요

2023-08-25 16:45 UTC, bimppap commented on src/main/java/CarRacing/Domain/Car.java
> +    private static final int MOVABLE_RPM_MIN = 4;
static 이어야 할 이유가 있나요?

2023-08-25 16:45 UTC, bimppap commented on src/main/java/CarRacing/Domain/Car.java
> +    public Position position;
상태가 변하지 않는 필드변수라면 final을 붙여주는게 안전합니다.

2023-08-25 16:45 UTC, bimppap commented on src/main/java/CarRacing/Domain/Car.java
> +    public Position position;
같은 접근제어자끼리는 개행 없이 붙여주세요.

2023-08-25 16:45 UTC, bimppap commented on src/main/java/CarRacing/Domain/Car.java
> +    public Position position;
접근제어자가 public인 이유가 있을까요?

2023-08-25 16:45 UTC, bimppap commented on src/main/java/CarRacing/Domain/Car.java
> +    }
이건 어디서 쓰이나요?

2023-08-25 16:45 UTC, bimppap commented on src/main/java/CarRacing/Domain/Cars.java
> +}
불필요한 개행은 제거해주세요

2023-08-25 16:45 UTC, bimppap commented on src/main/java/CarRacing/Domain/Cars.java
> +import CarRacing.Utils.RandomUtils;
쓰이지 않는 import는 제거해주세요

2023-08-25 16:45 UTC, bimppap commented on src/main/java/CarRacing/Domain/Name.java
> +    }
string format 👍

2023-08-25 16:45 UTC, bimppap commented on src/main/java/CarRacing/Domain/Position.java
> +    }
메서드는 위치가 생성자 아래에 있어야 합니다. getter의 경우 비즈니스 로직에 쓰이는 메서드보다 아래에 있어야 하는 점 유의해주세요.

2023-08-25 16:45 UTC, bimppap commented on src/main/java/CarRacing/Domain/Position.java
> +    }
private메서드는 사용되는 public 메서드 아래에 있는게 가독성에 좋습니다.

2023-08-25 16:45 UTC, bimppap commented on src/main/java/CarRacing/Domain/RacingGame.java
> +    }
이건 Car, Cars 객체에게 메세지를 보내는 방식으로 변경할 수 있을 것 같습니다. 다른 사람들 코드를 참고해보세요!

2023-08-25 16:45 UTC, bimppap commented on src/main/java/CarRacing/Domain/RacingGame.java
> +
Cars의 cars 필드변수는  private으로 하고 get으로 가져오게끔 수정하면 객체를 보다 안정적으로 쓸 수 있습니다.

2023-08-25 16:45 UTC, bimppap commented on src/main/java/CarRacing/Domain/RacingGame.java
> +    public Car moveCar(Car car){
외부에서 쓰이는 메서드가 아니라면 접근제어자는 private으로 바꿔주세요!

2023-08-25 16:45 UTC, bimppap commented on src/main/java/CarRacing/Utils/RandomUtils.java
> +        return random.nextInt(RANDOM_NUMBER);
random.nextInt(입력값)는 0~입력값 사이의 난수를 가져오는데 요구사항에서 주어진 범위는 1-9입니다

2023-08-25 16:45 UTC, bimppap commented on src/main/java/CarRacing/View/RacingGameOutputView.java
> +    private static final Scanner sc = new Scanner(System.in);
outputview에서는 scanner가 필요없지 않나요?

2023-08-25 16:45 UTC, bimppap commented on src/main/java/CarRacing/Domain/RacingGameFactory.java
> +public class RacingGameFactory {
racingGame과 racingGameFactory의 차이점은 무엇인가요?

2023-08-25 16:45 UTC, bimppap commented on src/main/java/CarRacing/Domain/RacingGameFactory.java
> +            throw new IllegalArgumentException();
어떤 에러인지 메세지를 전달해주면 더 좋을 것 같습니다

2023-08-25 16:46 UTC, bimppap commented on src/main/java/CarRacing/Controller/RacingGameController.java
> +    }
다른 클래스에서도 사용되지 않는 생성자는 지워주세요!

2023-08-26 16:12 UTC, SoyoungLee0918 commented on src/main/java/CarRacing/Domain/Car.java
> +    private static final int MOVABLE_RPM_MIN = 4;
그럴 이유가 없군요... 변경되지 않는 값이니까 static을 붙일 이유는 없네요...

2023-08-26 16:22 UTC, SoyoungLee0918 commented on src/main/java/CarRacing/Domain/RacingGameFactory.java
> +public class RacingGameFactory {
racingGarme은 RacingGameController에서 메소드만 불러와 수행할 수 있도록 게임을 실행하는 메소드를 모아두었고 RacingGameFactory는 실제로 게임의 실행에 쓰이지는 않지만 해당 메소드를 뒷받침해주고 규칙을 만족시키기 위한 메소드들을 모아두도록 설계했습니다.

2023-08-27 02:23 UTC, DyeonKim reviewed
수고하셨습니다~ 예외 사항을 정의하는 코드와 예외 발생 시 처리하는 코드가 아직 없던데 그걸 작성해주시면 될 거 같아요!
그리고 커밋메시지는 사용자의 요구사항에 맞춰 기능별로 나눠서 남기는 게 좋습니다.
ex. feat: 자동차 이름들 입력받고 자동차 생성

2023-08-27 02:23 UTC, DyeonKim commented on src/main/java/CarRacing/Domain/RacingGame.java
> +    public Car moveCar(Car car){
이건 리턴값이 필요없는 함수 같네요! void로 바꾸셔도 될 거 같습니다.

2023-08-27 02:23 UTC, DyeonKim commented on src/main/java/CarRacing/Domain/RacingGame.java
> +    }
저도 RS님 의견에 동의합니다! 단순히 생각해보면 이동은 경기가 있든 없든 차의 고유 기능이니까요! 해당 메소드의 기능이 어디에 포함될 지 고민해보시면 좋을 거 같습니다!

2023-08-27 02:23 UTC, DyeonKim commented on src/main/java/CarRacing/Domain/RacingGameFactory.java
> +public class RacingGameFactory {
주로 Factory라 이름이 붙은 클래스는 팩토리 디자인 패턴 방식에서 주로 쓰이는 이름입니다. 객체를 대신 생성하는 것이 주요 임무이고 목적은 클래스 간의 긴밀한 연결을 느슨하게하여 이후 유지보수를 더 쉽게 합니다. 해당 목적을 위해 쓰신 거 같지는 않아 클래스 이름을 바꾸길 권장합니다.
그리고  여기의 메소드들도 다른 클래스들로 옮겨도 될 거 같습니다. 어느 기능의 규칙을 만족시키기 위한 메소드인지 좀 더 세분화하여 생각해보시면 좋을 거 같아요.

2023-08-27 08:06 UTC, SoyoungLee0918 commented on src/main/java/CarRacing/Domain/RacingGame.java
> +    }
저는 RacingGame에서는 모든 경기 과정이 여기서 작동할 수 있도록 짰는데 좀 그런가요...? 제가 생각한 경기과정은 차의 이동 - 중간 경기 발표 - 가장 멀리간 차 찾기로 생각했습니다. 이외의 입출력은 따로 빼어서 설계 했습니다.

2023-08-27 09:04 UTC, bimppap approved these changes
피드백 반영할 시간이 부족했을텐데도 빠르게 적용해주셨네요
수고하셨습니다!!

2023-08-27 09:04 UTC, merged